Tarea2NCapas/src/com/uca/capas/domain/Empleado.java
package com.uca.capas.domain;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(schema = "public", name = "empleado")
public class Empleado {
	
	@Id
	@GeneratedValue(generator = "empleado_c_empleado_seq", strategy = GenerationType.AUTO)
	@SequenceGenerator(name = "empleado_c_empleado_seq", sequenceName = "public.empleado_c_empleado_seq", allocationSize = 1)
	@Column(name = "id_empleado")
	private Integer id_empleado;

	@Column(name = "empleado_nombre")
	private String eNombre;

	@Column(name = "empleado_edad")
	private Integer eEdad;

	@Column(name = "empleado_genero")
	private String eGenero;

	@Column(name = "empleado_estado")
	private Boolean eEstado;
	
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "empleado_sucursal")
	private Sucursal empleado_sucursal;
	
	public Empleado() {

	}

	public Empleado(Integer id_empleado, String eNombre,
			Integer eEdad,
			String eGenero,
			Boolean eEstado, 
			Sucursal empleado_sucursal) {
		super();
		this.id_empleado = id_empleado;
		this.eNombre = eNombre;
		this.eEdad = eEdad;
		this.eGenero = eGenero;
		this.eEstado = eEstado;
		this.empleado_sucursal = empleado_sucursal;
	}

	public Integer geteId() {
		return id_empleado;
	}

	public void seteId(Integer id_empleado) {
		this.id_empleado = id_empleado;
	}

	public String geteNombre() {
		return eNombre;
	}

	public void seteNombre(String eNombre) {
		this.eNombre = eNombre;
	}

	public Integer geteEdad() {
		return eEdad;
	}

	public void seteEdad(Integer eEdad) {
		this.eEdad = eEdad;
	}

	public String geteGenero() {
		return eGenero;
	}

	public void seteGenero(String eGenero) {
		this.eGenero = eGenero;
	}

	public Boolean geteEstado() {
		return eEstado;
	}

	public void seteEstado(Boolean eEstado) {
		this.eEstado = eEstado;
	}

	public Sucursal getempleado_sucursal() {
		return empleado_sucursal;
	}

	public void setempleado_sucursal(Sucursal eSucursal) {
		this.empleado_sucursal = eSucursal;
	}

	public String getEstadoMod() {
		return this.eEstado == null ? "" : this.eEstado == true ? "Activo" : "Inactivo";
	}


}

Tarea2NCapas/src/com/uca/capas/domain/Sucursal.java
package com.uca.capas.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(schema = "public", name = "sucursal")
public class Sucursal {
	
	@Id
	@GeneratedValue(generator = "sucursal_c_sucursal_seq", strategy = GenerationType.AUTO)
	@SequenceGenerator(name = "sucursal_c_sucursal_seq", sequenceName = "public.sucursal_c_sucursal_seq", allocationSize = 1)
	@Column(name = "id_sucursal")
	private Long sId;

	@Column(name = "sucursal_nombre")
	private String sNombre;

	@Column(name = "sucursal_ubicacion")
	private String sUbicacion;

	@Column(name = "sucursal_horario")
	private String sHorarios;

	@Column(name = "sucursal_mesas")
	private Integer sNMesas;

	@Column(name = "sucursal_nomgerente")
	private String sNomGerente;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "empleado_sucursal")
	private List<Empleado> sEmpleados;
	
	public Long getsId() {
		return sId;
	}

	public void setsId(Long sId) {
		this.sId = sId;
	}

	public String getsNombre() {
		return sNombre;
	}

	public void setsNombre(String sNombre) {
		this.sNombre = sNombre;
	}

	public String getsUbicacion() {
		return sUbicacion;
	}

	public void setsUbicacion(String sUbicacion) {
		this.sUbicacion = sUbicacion;
	}

	public String getsHorarios() {
		return sHorarios;
	}

	public void setsHorarios(String sHorarios) {
		this.sHorarios = sHorarios;
	}

	public Integer getsNMesas() {
		return sNMesas;
	}

	public void setsNMesas(Integer sNMesas) {
		this.sNMesas = sNMesas;
	}

	public String getsNomGerente() {
		return sNomGerente;
	}

	public void setsNomGerente(String sNomGerente) {
		this.sNomGerente = sNomGerente;
	}

	public List<Empleado> getsEmpleados() {
		return sEmpleados;
	}

	public void setsEmpleados(List<Empleado> sEmpleados) {
		this.sEmpleados = sEmpleados;
	}
	
	public Sucursal() {

	}

	public Sucursal(Long sId, String sNombre, String sUbicacion, String sHorarios, Integer sNMesas,
			String sNomGerente, List<Empleado> sEmpleados) {
		super();
		this.sId = sId;
		this.sNombre = sNombre;
		this.sUbicacion = sUbicacion;
		this.sHorarios = sHorarios;
		this.sNMesas = sNMesas;
		this.sNomGerente = sNomGerente;
		this.sEmpleados = sEmpleados;
	}

}

Tarea2NCapas/src/com/uca/capas/domain/Usuario.java
package com.uca.capas.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(schema = "public", name = "usuario")
public class Usuario {
	@Id
	@Column(name = "id_usuario")
	private Integer usuario_id;

	@Column(name = "nombreusuario")
	private String uNombre;

	@Column(name = "claveusuario")
	private String uContra;
	
	public Integer getUsuario_id() {
		return usuario_id;
	}

	public void setUsuario_id(Integer usuario_id) {
		this.usuario_id = usuario_id;
	}

	public String getuNombre() {
		return uNombre;
	}

	public void setuNombre(String uNombre) {
		this.uNombre = uNombre;
	}

	public String getuContra() {
		return uContra;
	}

	public void setuContra(String uContra) {
		this.uContra = uContra;
}

}

Tarea2NCapas/src/com/uca/capas/controller/LoginController.java
package com.uca.capas.controller;

import org.jboss.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.uca.capas.domain.Usuario;
import com.uca.capas.service.UsuarioService;

@Controller
public class LoginController {
	

static Logger log = Logger.getLogger(LoginController.class.getName());

	@Autowired
	UsuarioService usuarioService;
	
	@GetMapping("/")
	public ModelAndView initLogin() {
		return new ModelAndView("redirect:/login");
	}
	
	@GetMapping("/login")
	public ModelAndView initLoginOficial() {
		ModelAndView mav = new ModelAndView();
		mav.setViewName("login");
		return mav;
	}
	
	@PostMapping(value = "/validate")
	public ModelAndView validate(@RequestParam(value = "username") String username,
			@RequestParam(value = "password") String password) {
		ModelAndView mav = new ModelAndView();
		Usuario usuarioLogin = usuarioService.findByUserAndPass(username, password);
		if (usuarioLogin != null) {
			if (usuarioLogin.getuNombre() != null) {
				if (usuarioLogin.getuNombre().equals(username)) {
					if (usuarioLogin.getuContra().equals(password)) {
						mav.setViewName("home");
						return new ModelAndView("redirect:/home");
					}
				}
			}
		}
		return new ModelAndView("redirect:/login");
}
}

Tarea2NCapas/WebContent/WEB-INF/views/agregar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Agregue una sucursal de Rústico</title>
</head>
<body>
<h1>${message }</h1>
<form:form action="${pageContext.request.contextPath}/guardar" method="POST" modelAttribute="sucursal">
		<label>Ingrese el nombre de la sucursal: </label>
		<form:input type='text' path='sNombre' value='${sucursal.sNombre}'/>
		<label>Ingrese la ubicacion de la sucursal: </label>
		<form:input type='text' path='sUbicacion' value='${sucursal.sUbicacion}'/>
		<label>Ingrese los horarios de la sucursal: </label>
		<form:input type='text' path='sHorarios' value='${sucursal.sHorarios}'/>
		<label>Ingrese el numero de mesas de la sucursal: </label>
		<form:input type='text' path='sNMesas' value='${sucursal.sNMesas}'/>
		<label>Ingrese el nombre del gerente de la sucursal: </label>
		<form:input type='text' path='sNomGerente' value='${sucursal.sNomGerente}'/>
		<button onclick="window.location.href = '${pageContext.request.contextPath}/guardar'">Insertar</button>
	</form:form>
</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/agregarEmpleado.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Agregue un empleado de Rústico</title>
</head>
<body>
<h1>${message }</h1>
<form:form action="${pageContext.request.contextPath}/guardarEmpleado" method="POST" modelAttribute="empleado">
		<label>Ingrese el nombre del empleado: </label>
		<form:input type='text' path='eNombre' value='${empleado.eNombre}'/>
		<label>Ingrese la edad del empleado: </label>
		<form:input type='text' path='eEdad' value='${empleado.eEdad}'/>
		<label>Ingrese el genero del empleado: </label>
		<form:input type='text' path='eGenero' value='${empleado.eGenero}'/>
		<label>Ingrese el estado del empleado: </label>
		<form:input type='text' path='eEstado' value='${empleado.eEstado}'/>
		<label>Ingrese el nombre de la sucursal para la que trabaja: </label>
		<form:input type='text' path='empleado_sucursal' value='${empleado.empleado_sucursal}'/>
		<button onclick="window.location.href = '${pageContext.request.contextPath}/guardarEmpleado'">Insertar</button>
	</form:form>
</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/editar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edite una sucursal de Rústico</title>
</head>
<body>
	<h3>${message}</h3>
	<form:form method = "POST" action = "${pageContext.request.contextPath}/actualizar" ModelAttribute = "sucursal">
		<table>
			<thead>
				<tr>
					<th>Valor a editar</th>
					<th>Valor actual</th>
					<th>Nuevo valor</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Id de la sucursal:</td>
					<td>${sucursal.sId}</td>
					<td><input type = "text" name = "sId" path = "sId" value = "${sucursal.sId}"></td>
				</tr>
				<tr>
					<td>Nombre de la sucursal:</td>
					<td>${sucursal.sNombre}</td>
					<td><input type = "text" name = "sNombre" path = "sNombre" value = "${sucursal.sNombre}"></td>
				</tr>
				<tr>
					<td>Ubicacion de la sucursal:</td>
					<td>${sucursal.sUbicacion}</td>
					<td><input type = "text" name = "sUbicacion" path = "sUbicacion" value = "${sucursal.sUbicacion}"></td>
				</tr>
				<tr>
					<td>Horario de la sucursal:</td>
					<td>${sucursal.sHorarios}</td>
					<td><input type = "text" name = "sHorarios" path = "sHorarios" value = "${sucursal.sHorarios}"></td>
				</tr>
				<tr>
					<td>Numero de mesas de la sucursal:</td>
					<td>${sucursal.sNMesas}</td>
					<td><input type = "text" name = "sNMesas" path = "sNMesas" value = "${sucursal.sNMesas}"></td>
				</tr>
				<tr>
					<td>Nombre del gerente de la sucursal:</td>
					<td>${sucursal.sNomGerente}</td>
					<td><input type = "text" name = "sNomGerente" path = "sNomGerente" value = "${sucursal.sNomGerente}"></td>
				</tr>
			</tbody>
		</table>
		<input type = "submit" name = "editar" value = "editar">
	</form:form>
</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/editarEmpleado.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edite un empleado de Rústico</title>
</head>
<body>
	<h3>${message}</h3>
	<form:form method = "POST" action = "${pageContext.request.contextPath}/actualizarEmpleado?id=${Sucursal}" ModelAttribute = "empleado">
		<table>
			<thead>
				<tr>
					<th>Valor a editar</th>
					<th>Valor actual</th>
					<th>Nuevo valor</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Nombre del empleado:</td>
					<td>${empleado.eNombre}</td>
					<td><input type = "text" name = "eNombre" path = "eNombre" value = "${empleado.eNombre}"></td>
				</tr>
				<tr>
					<td>Edad del empleado:</td>
					<td>${empleado.eEdad}</td>
					<td><input type = "text" name = "eEdad" path = "eEdad" value = "${empleado.eEdad}"></td>
				</tr>
				<tr>
					<td>Genero del empleado:</td>
					<td>${empleado.eGenero}</td>
					<td><input type = "text" name = "eGenero" path = "eGenero" value = "${empleado.eGenero}"></td>
				</tr>
				<tr>
					<td>Estado del empleado:</td>
					<td>${empleado.estadoMod}</td>
					<td><input type = "text" name = "eEstado" path = "eEstado" value = "${empleado.estadoMod}"></td>
				</tr>
			</tbody>
		</table>
		<input type = "submit" name = "editarEmpleado" value = "editarEmpleado">
	</form:form>
</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<!DOCTYPE html>
<html>
<head>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<meta charset="UTF-8">
<meta charset="UTF-8">
<title>Rústico Restaurante</title>
</head>
<body>
<div class="container">
	    <div class="row col-md-6 col-md-offset-2">
	    <h1>${message}</h1>
		    <table class="table table-hover">
			    <thead>
				    <tr>
				    	<th class="text-center">Nombre de la sucursal</th>
				        <th class="text-center">Ubicacion</th>
				        <th class="text-center">Opciones</th>
				    </tr>
				</thead>
			    <c:forEach items="${sucursales}" var="sucursales">
			    <tr>
			        <td class="text-center"><b>${sucursales.sNombre}</b></td>
			        <td class="text-center">${sucursales.sUbicacion}</td>
			        <td class="text-center">
			        	<button class='btn btn-info btn-xs' type="button" onclick="window.location.href = '${pageContext.request.contextPath}/verPerfil?id=${sucursales.sId}'">Ver perfil</button>
			        	<button class='btn btn-info btn-xs' type="button" onclick="window.location.href = '${pageContext.request.contextPath}/editar?id=${sucursales.sId}'">Editar</button>
			        	<button class="btn btn-danger btn-xs" type="button" onclick="window.location.href = '${pageContext.request.contextPath}/eliminar?id=${sucursales.sId}'">Eliminar</button>
			        </td>
			    </tr>
			    </c:forEach>
		    </table>
		    <form:form action = "${pageContext.request.contextPath}/agregar" method = "POST">
			<input class="btn btn-primary btn-xs pull-center" type = "submit" value = "Agregar Sucursal">
			</form:form>
	    </div>
	    
	</div>

</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>


<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>


<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="./resources/css/main.css">
</head>
<body>
	
	
	<div class="container-login100">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">
			<form:form action="validate" method="post" id="Login" class="login100-form">
				<span class="login100-form-title p-b-37">
					Rústico Restaurant
				</span>

				<div class="wrap-input100 m-b-20" data-validate="Enter username">
					<input class="input100" type="text" name="username" id = "usernameInput" placeholder="username">
				</div>

				<div class="wrap-input100 m-b-25" data-validate = "Enter password">
					<input class="input100" type="password" name="password" id = "passwordInput" placeholder="password">
				</div>

				<div class="container-login100-form-btn">
					<button type="submit" class="login100-form-btn">
						Ingresar
					</button>
				</div>
			</form:form>

			
		</div>
	</div>

</body>
</html>

Tarea2NCapas/WebContent/WEB-INF/views/verPerfil.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href="./resources/css/home.css">
	<meta charset="UTF-8">
	<title>Ver perfil del restaurante</title>
</head>
<body>
	<h2 class="text-center"><b>Perfil de sucursal: ${sucursal.sNombre}</b></h2>
	<h4 class="text-center">Ubicacion de la sucursal: ${sucursal.sUbicacion}</h4>
	<h4 class="text-center">Horarios de la sucursal: ${sucursal.sHorarios}</h4>
	<h4 class="text-center">Numero de mesas: ${sucursal.sNMesas}</h4>
	<h4 class="text-center">Nombre del gerente: ${sucursal.sNomGerente}</h4>
	<div class="container">
	    <div class="row col-md-6 col-md-offset-2 custyle">
		    <table class="table table-striped custab">
			    <thead>
				    <tr>
				    	<th class="text-center">Nombre del empleado</th>
				        <th class="text-center">Edad</th>
				        <th class="text-center">Genero</th>
				        <th class="text-center">Estado</th>
				        <th class="text-center">Acciones</th>
				    </tr>
				</thead>
			    <c:forEach items="${empleados}" var="empleados">
			    <tr>
			        <td class="text-center"><b>${empleados.eNombre}</b></td>
			        <td class="text-center">${empleados.eEdad}</td>
			        <td class="text-center">${empleados.eGenero}</td>
			        <td class="text-center">${empleados.estadoMod}</td>
			        <td class="text-center">
			        	<button class='btn btn-info btn-xs' type="button" onclick="window.location.href = '${pageContext.request.contextPath}/editarEmpleado?id=${sucursal.sId}&eid=${empleados.eId}'">Editar</button>
			        	<button class="btn btn-danger btn-xs" type="button" onclick="window.location.href = '${pageContext.request.contextPath}/borrarEmpleado?id=${sucursal.sId}&eid=${empleados.eId}'">Borrar</button>
			        </td>
			    </tr>
			    </c:forEach>
		    </table>  
	    </div>
		<button class="btn btn-primary btn-xs pull-center" type="button" onclick="window.location.href = '${pageContext.request.contextPath}/home'">Regresar</button>
		<button class="btn btn-primary btn-xs pull-center" type="button" onclick="window.location.href = '${pageContext.request.contextPath}/agregarEmpleado'">Agregar empleado</button>
	</div>
</body>
</html>